#!/bin/bash

mkdir -p dependencies/
cd dependencies/

git clone https://github.com/pheymann/specdris.git
cd specdris
idris --install specdris.ipkg
cd ../

git clone https://github.com/idris-hackers/idris-free.git
cd idris-free
idris --install idris-free.ipkg
cd  ../
